# syntax=docker/dockerfile:1

ARG REPO=whittlem/pycryptobot

FROM ghcr.io/${REPO}/pycryptobot:latest

EXPOSE 5000/tcp

# Pass parameters to the container run or mount your config.json into /app/
ENTRYPOINT [ "python3", "-u", "websvc.py" ]
